services:
  postgresql:
    container_name: pg_sql
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: kafu
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./postgres/init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      - kafu-network
    restart: unless-stopped
    healthcheck:
      test: "exit 0"

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:9.1.0
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - kafu-network
    restart: unless-stopped
    depends_on:
      - postgresql

  keycloak:
    image: quay.io/keycloak/keycloak:26.1.2
    command: start-dev --import-realm
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HOSTNAME: localhost

      KC_DB_URL_HOST: postgresql
      KC_DB_URL_DATABASE: keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
      KC_DB_SCHEMA: public

    networks:
      - kafu-network
    ports:
      - "9098:8080"
    depends_on:
      postgresql:
        condition: service_healthy

    volumes:
      - keycloak:/opt/keycloak/data
      - ./keycloak/imports:/opt/keycloak/data/import

  kafu-app:
    build: .
    container_name: kafu-app
    ports:
      - "8080:8080"
    networks:
      - kafu-network
    depends_on:
      - postgresql
      - keycloak
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgresql:5432/kafu
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_JPA_HIBERNATE_DDL_AUTO: validate
      KEYCLOAK_AUTH_SERVER_URL: http://keycloak:8080
      KEYCLOAK_CLIENT_SECRET: my-super-secret-client-secret
      SWAGGER_AUTH_SERVER_URL: http://localhost:9098
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_KEY: ${AWS_SECRET_KEY}
      AWS_REGION: ${AWS_REGION}
      AWS_S3_BUCKET: ${AWS_S3_BUCKET}
volumes:
  postgres:
  pgadmin:
  keycloak:

networks:
  kafu-network: