services:
  postgresql:
    container_name: pg_sql
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - kafu-network
    restart: unless-stopped
    healthcheck:
      test: "exit 0"

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:9.1.0
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - kafu-network
    restart: unless-stopped
    depends_on:
      - postgresql

  keycloak:
    image: quay.io/keycloak/keycloak:26.1.2
    command: start-dev
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HOSTNAME: localhost

      KC_DB_URL_HOST: postgresql
      KC_DB_URL_DATABASE: keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
      KC_DB_SCHEMA: public

    networks:
      - kafu-network
    ports:
      - "9098:8080"
    depends_on:
      postgresql:
        condition: service_healthy

    volumes:
      - keycloak:/opt/keycloak/data


volumes:
  postgres:
  pgadmin:
  keycloak:

networks:
  kafu-network: