spring:
  application:
    name: kafu
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${keycloak.auth-server-url}/realms/${keycloak.realm}
  datasource:
    url: jdbc:postgresql://localhost:5432/kafu
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

springdoc:
  swagger-ui:
    oauth:
      client-id: ${keycloak.client-id}
      realm: ${keycloak.realm}
      appName: kafu
swagger:
  auth-server-url: http://localhost:9098
  realm: kafu-realm

server:
  port: 8080

keycloak:
  auth-server-url: http://localhost:9098
  realm: kafu-realm
  client-id: kafu-client
  client-secret: my-super-secret-client-secret

jwt:
  auth:
    converter:
      resource-id: kafu-realm
      principle-attribute: preferred_username


aws:
  accessKeyId: ${AWS_ACCESS_KEY_ID}
  secretKey: ${AWS_SECRET_KEY}
  region: ${AWS_REGION}
  s3:
    bucket: ${AWS_S3_BUCKET}
    maxFileSize: 10485760  # 10MB in bytes
    allowedFileTypes: image/jpeg,image/png,image/jpg,application/pdf,application/msword,application/vnd.openxmlformats-officedocument.wordprocessingml.document


payment:
  stripe:
    apiKey: ${PAYMENT_STRIPE_APIKEY}
    webhookSecret: ${PAYMENT_STRIPE_webhookSecret}